/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PartsRouteImport } from './routes/parts'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CharterRouteImport } from './routes/charter'
import { Route as AppRouteImport } from './routes/app'
import { Route as AircraftRouteImport } from './routes/aircraft'
import { Route as AdvisoryRouteImport } from './routes/advisory'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnginesIndexRouteImport } from './routes/engines/index'
import { Route as EnginesEngine360RouteImport } from './routes/engines/engine-360'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsRoute = PartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CharterRoute = CharterRouteImport.update({
  id: '/charter',
  path: '/charter',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AircraftRoute = AircraftRouteImport.update({
  id: '/aircraft',
  path: '/aircraft',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisoryRoute = AdvisoryRouteImport.update({
  id: '/advisory',
  path: '/advisory',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnginesIndexRoute = EnginesIndexRouteImport.update({
  id: '/engines/',
  path: '/engines/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnginesEngine360Route = EnginesEngine360RouteImport.update({
  id: '/engines/engine-360',
  path: '/engines/engine-360',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory': typeof AdvisoryRoute
  '/aircraft': typeof AircraftRoute
  '/app': typeof AppRoute
  '/charter': typeof CharterRoute
  '/contact': typeof ContactRoute
  '/legal': typeof LegalRoute
  '/parts': typeof PartsRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/engines/engine-360': typeof EnginesEngine360Route
  '/engines/': typeof EnginesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory': typeof AdvisoryRoute
  '/aircraft': typeof AircraftRoute
  '/app': typeof AppRoute
  '/charter': typeof CharterRoute
  '/contact': typeof ContactRoute
  '/legal': typeof LegalRoute
  '/parts': typeof PartsRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/engines/engine-360': typeof EnginesEngine360Route
  '/engines': typeof EnginesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory': typeof AdvisoryRoute
  '/aircraft': typeof AircraftRoute
  '/app': typeof AppRoute
  '/charter': typeof CharterRoute
  '/contact': typeof ContactRoute
  '/legal': typeof LegalRoute
  '/parts': typeof PartsRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/engines/engine-360': typeof EnginesEngine360Route
  '/engines/': typeof EnginesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advisory'
    | '/aircraft'
    | '/app'
    | '/charter'
    | '/contact'
    | '/legal'
    | '/parts'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/engines/engine-360'
    | '/engines/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advisory'
    | '/aircraft'
    | '/app'
    | '/charter'
    | '/contact'
    | '/legal'
    | '/parts'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/engines/engine-360'
    | '/engines'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advisory'
    | '/aircraft'
    | '/app'
    | '/charter'
    | '/contact'
    | '/legal'
    | '/parts'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/engines/engine-360'
    | '/engines/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvisoryRoute: typeof AdvisoryRoute
  AircraftRoute: typeof AircraftRoute
  AppRoute: typeof AppRoute
  CharterRoute: typeof CharterRoute
  ContactRoute: typeof ContactRoute
  LegalRoute: typeof LegalRoute
  PartsRoute: typeof PartsRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  EnginesEngine360Route: typeof EnginesEngine360Route
  EnginesIndexRoute: typeof EnginesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts': {
      id: '/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof PartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charter': {
      id: '/charter'
      path: '/charter'
      fullPath: '/charter'
      preLoaderRoute: typeof CharterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aircraft': {
      id: '/aircraft'
      path: '/aircraft'
      fullPath: '/aircraft'
      preLoaderRoute: typeof AircraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisory': {
      id: '/advisory'
      path: '/advisory'
      fullPath: '/advisory'
      preLoaderRoute: typeof AdvisoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engines/': {
      id: '/engines/'
      path: '/engines'
      fullPath: '/engines/'
      preLoaderRoute: typeof EnginesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engines/engine-360': {
      id: '/engines/engine-360'
      path: '/engines/engine-360'
      fullPath: '/engines/engine-360'
      preLoaderRoute: typeof EnginesEngine360RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvisoryRoute: AdvisoryRoute,
  AircraftRoute: AircraftRoute,
  AppRoute: AppRoute,
  CharterRoute: CharterRoute,
  ContactRoute: ContactRoute,
  LegalRoute: LegalRoute,
  PartsRoute: PartsRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  EnginesEngine360Route: EnginesEngine360Route,
  EnginesIndexRoute: EnginesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
